### ISSUE TITLE
Wekan integration

### ISSUE THREAD

**Issue by helioguardabaxo** [Ben0it-T/trello-board-exporter#1]
Hi, @Ben0it-T!

Would you intend to integrate this solution on Wekan as a native feature?
Or to implement json export and customize Wekan to upload attachments?

**Comment by Ben0it-T** [comment]
Hi @helioguardabaxo
Wekan already has export features (json, xlsx, csv).
I did not intend to implement this type of export on Wekan  (board as xlsx and cards as docx _with or without template_) but it is certainly doable.

Wekan also has a feature to import a board from Trello (json). However, I don't know anymore if this import can import attachments.  Seems to me that it works with a public board but doesn't work with a private board.

**Comment by helioguardabaxo** [comment]
Currently wekan does not import the attachments. It is giving an error in the importBoard method.
I will think about an alternative to ease the migration of boards from Trello to Wekan to help non-technical users.

Thanks!

**Comment by Ben0it-T** [comment]
hmmm 
maybe a Chrome extension would be easier... something like this https://github.com/llad/export-for-trello for example (but specific for Wekan). It could be easier to replace cards.attachments.url with cards.attachments.file in the json export...
but ok, that wouldn't be a native feature.

**Comment by Ben0it-T** [comment]
@helioguardabaxo
I made a little chrome extension which allows to download attachments and/or export board as JSON including attachments as dataURL in cards.attachments.file (and remove cards.attachments.url)
https://github.com/Ben0it-T/trello-attachments-export

Maybe it will interest you or give you some ideas.
I'll complete readme later
